version: "3"

services:
  postgres:
    image: 'postgres:13'
    container_name: 'postgres-13-java-aop'
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=java'
  app:
    build: ./
    container_name: "java"
    ports:
    - "8081:8081"
